# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170213_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='unfollow',
            name='unfollow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Unfollow',
        ),
    ]
