# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20170220_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
